language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"

# install dependencies
install: 
  -pip install -r requirements.txt
  -pip install codecov

# run scripts
script:
  - coverage erase
  - coverage run app/yaba_test.py && coverage report app/yaba_test.py

after_success:
  - codecov