language: python

python:
    - "3.5"
    - "3.6"

env:
  - config_file_name=app/credentials.yaml

# install dependencies
install: 
  - pip install -r app/requirements.txt
  - pip install codecov

# run scripts
script:
  - coverage erase
  - coverage run app/yaba_test.py && coverage report app/yaba_test.py

after_success:
  - codecov