version: '3'

services:
  # postgresql with postgis docker image to hold the data
  postgres:
    image: mdillon/postgis:9.5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bety
    ports:
      - 9000:5432
    restart: unless-stopped
  # BETY docker image
  bety:
    image: pecan/bety:${BRANCH:-latest}
    ports:
      - 8000:8000
    networks:
      - bety
    environment:
      - INITIALIZE_URL=-w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz
      - REMOTE_SERVERS=6
      - UNICORN_WORKER_PROCESSES=1
      - SECRET_KEY_BASE=thisissomereallllllylongsecretkeyandshouldbelongerthanthis
    depends_on:
      - postgres
    restart: unless-stopped

  yaba_api:
    build: ./app
    networks:
      - bety
    volumes:
      - ./app:/code
    ports:
      - 5001:5000
    depends_on:
      - postgres
      
volumes:
  postgres:

networks:
  bety:


  