# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: YABA client tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: client

    steps:
      - name: Checkout Code        
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
            python-version: 3.7

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip -m install pytest
              pip -m install pytest-cov
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest and generate coverage report
        run: |
              pytest yaba_client_test/test_yaba_client.py --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1