name: YABA interface tests

on:
  push:
    branches: [ master, containerize ]
  pull_request:
    branches: [ master, containerize ]

jobs:
  interface_test:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: interface

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1